FROM python:3.12-slim

WORKDIR /app

COPY base_image_creation/fastapi/requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt




