name: Deploy ansible frontend
on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main
    #     paths:
    #         - 'streamlit_app/**'
    # workflow_run:
    #     workflows: ["Frontend Docker Build and Push"]
    #     types:
    #         - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Install Ansible
              run: |
                sudo apt update
                sudo apt install -y ansible
            - name: Create pem file
              run: |
                echo "${{ secrets.PEM_SSH_KEY }}" > ansible.pem
                chmod 600 ansible.pem
            - name: Create Ansible Hosts File
              run: |
                echo "[frontends]" > frontends.ini
                echo "${{secrets.FRONTEND_URL}} ansible_user=ubuntu ansible_ssh_private_key_file=ansible.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> frontends.ini
            - name: Run Ansible Playbook
              run: |
                    ansible-playbook -i frontends.ini deploy_frontend.yml --extra-vars "API_URL=${{ secrets.API_URL }} docker_user_name=${{ secrets.DOCKER_USERNAME }} docker_password=${{ secrets.DOCKER_PASSWORD }} GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} REDIRECT_URI=http://${{ secrets.FRONTEND_URL }}.nip.io:8501 AWS_REGION=${{ vars.AWS_REGION }}"
