name: Deploy ansible microservice
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'Predict_Microservice/**'
    workflow_run:
        workflows: ["Predict Microservice"]
        types:
            - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Install Ansible
              run: |
                sudo apt update
                sudo apt install -y ansible
            - name: Create pem file
              run: |
                echo "${{ secrets.PEM_SSH_KEY }}" > ansible.pem
                chmod 600 ansible.pem
            - name: Create Ansible Hosts File
              run: |
                echo "[microservices]" > microservices.ini
                echo "ansible_user=ubuntu" >> microservices.ini
                echo "${{secrets.API_URL}}" >> microservices.ini
                echo "ansible_ssh_private_key_file=ansible.pem" >> microservices.ini
            - name: Run Ansible Playbook
              run: |
                    ansible-playbook -i microservices.ini deploy_microservice.yml --extra-vars "docker_user_name=${{ secrets.DOCKER_USERNAME }} docker_password=${{ secrets.DOCKER_PASSWORD }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

